version: "3.9"

services:
  web:
    build: .
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      - REDIS_HOST=redis_service
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      custom_net:
        aliases:
          - web_service

  redis:
    image: redis:alpine
    container_name: redis_broker
    ports:
      - "6379:6379"
    networks:
      custom_net:
        aliases:
          - redis_service   # 🔑 barqaror nom

  celery:
    build: .
    container_name: celery_worker
    command: celery -A src worker -l info
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      - REDIS_HOST=redis_service
    depends_on:
      - redis
      - web
    networks:
      custom_net:
        aliases:
          - celery_service

  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A src beat -l info
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      - REDIS_HOST=redis_service
    depends_on:
      - redis
      - web
    networks:
      custom_net:
        aliases:
          - celery_beat_service

volumes:
  db_data:

networks:
  custom_net:
    driver: bridge
