# Generated by Django 5.2.5 on 2025-08-25 09:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0002_alter_card_balance_alter_card_card_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('en', models.CharField(max_length=255)),
                ('ru', models.CharField(max_length=255)),
                ('uz', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(default=uuid.uuid4, editable=False, max_length=40, unique=True)),
                ('sender_card_expiry', models.CharField(max_length=5)),
                ('sender_phone', models.CharField(max_length=20)),
                ('receiver_phone', models.CharField(max_length=20)),
                ('sending_amount', models.PositiveIntegerField()),
                ('currency', models.CharField(choices=[('643', 'RUB'), ('840', 'USD'), ('860', 'UZS')])),
                ('receiving_amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('state', models.CharField(choices=[('created', 'created'), ('confirmed', 'confirmed'), ('cancelled', 'cancelled')])),
                ('try_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('otp', models.CharField(max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('receiver_card_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_transfers', to='card.card')),
                ('sender_card_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='send_transfers', to='card.card')),
            ],
        ),
    ]
