# Generated by Django 5.2.5 on 2025-09-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('en', models.CharField(max_length=255)),
                ('ru', models.CharField(max_length=255)),
                ('uz', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(default='', editable=False, max_length=40, unique=True)),
                ('sender_id', models.TextField()),
                ('receiver_id', models.TextField()),
                ('sending_amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(choices=[('643', 'RUB'), ('840', 'USD'), ('860', 'UZS')], max_length=3)),
                ('receiving_amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('state', models.IntegerField(choices=[(1, 'created'), (2, 'confirmed'), (3, 'cancelled')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
