# Generated by Django 5.2.5 on 2025-10-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='exchange_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='rate_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
