# Generated by Django 5.2.5 on 2025-08-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='ext_id',
            field=models.CharField(default='', editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='receiver_card_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='sender_card_number',
            field=models.CharField(max_length=20),
        ),
    ]
