# Generated by Django 5.2.5 on 2025-09-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='currency',
            field=models.CharField(choices=[('643', 'RUB'), ('840', 'USD'), ('860', 'UZS')], max_length=3),
        ),
    ]
