# Generated by Django 5.2.5 on 2025-08-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_alter_transfer_ext_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='state',
            field=models.CharField(choices=[(1, 'created'), (2, 'confirmed'), (3, 'cancelled')]),
        ),
    ]
