# Generated by Django 5.2.5 on 2025-09-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_alter_transfer_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='otp',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
