# Generated by Django 5.2.5 on 2025-08-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0003_alter_transfer_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='state',
            field=models.IntegerField(choices=[(1, 'created'), (2, 'confirmed'), (3, 'cancelled')], default=1),
        ),
    ]
